# Generated by Django 5.2.5 on 2025-09-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        help_text="Уникальный идентификатор пользователя в Telegram (int64).",
                        unique=True,
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="Чат для доставки уведомлений (обычно совпадает с telegram_user_id).",
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username в Telegram (если есть).",
                        max_length=64,
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Когда выполнена привязка."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Флаг активности привязки (если пользователь удалил бота — выключаем).",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Пользователь, к которому привязан Telegram-аккаунт.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль Telegram",
                "verbose_name_plural": "Профили Telegram",
                "indexes": [
                    models.Index(
                        fields=["telegram_user_id"], name="tg_profile_user_id_idx"
                    ),
                    models.Index(fields=["chat_id"], name="tg_profile_chat_id_idx"),
                ],
            },
        ),
    ]
